services:
  postgres:
    image: postgres:15
    container_name: finance-app-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: financeapp
    volumes:
      - ./.postgres/financeapp:/var/lib/postgresql/data
    ports:
      - "5432:5432"
